# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FairFuture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FairFuture
	pod 'Locksmith'
    pod 'BEMCheckBox'
    pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
    pod 'GoogleSignIn', '~> 4.1.1'
    pod 'Cloudinary', '~> 2.0'
    pod 'SwiftyJSON', '~> 4.0'
end
